version: '2.2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:7.0
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
      - ./mongodb-persistence:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local
